package org.uom.fyp.engine

import com.perfdynamics.pdq.PDQ

/**
 * Contains utility methods that extract values generated by PDQ and transfers
 * them to properties in the actual data structures within the road graph
 * network.
 */
object PDQProperties {

  /**
   * Copies values from properties within the PDQ object to the given road network.
   * @param pdq PDQ object.
   * @param network Road network.
   */
  def pdqNodesToRoadNetwork(pdq: PDQ, network: RoadNetwork) = {

  }

}
